/*
 * ParticipantCaller API
 *
 * API for the app ParticipantCaller
 *
 * API version: 1.0.0
 * Contact: aiqueneldar@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Role struct {
	// UUID for the role
	Id string `json:"id,omitempty"`
	// Human readable name of the role
	Name string `json:"name,omitempty"`

	Abilities []string `json:"abilities,omitempty"`
}
