/*
 * ParticipantCaller API
 *
 * API for the app ParticipantCaller
 *
 * API version: 1.0.0
 * Contact: aiqueneldar@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ability struct {
	// UUID of the ability
	Id string `json:"id"`
	// Human readable name of the ability
	Name string `json:"name"`
	// Ability that an entity posseses. Examples are \"Create\", \"Modify\", \"Delete\", etc.
	Description string `json:"description"`
}
