/*
 * ParticipantCaller API
 *
 * API for the app ParticipantCaller
 *
 * API version: 1.0.0
 * Contact: aiqueneldar@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type EventNew struct {
	// Human readable name
	Name string `json:"name"`

	Locations []string `json:"locations"`

	Enteties []string `json:"enteties"`
	// Date and time the event event will start. 
	Date time.Time `json:"date"`
}
