/*
 * ParticipantCaller API
 *
 * API for the app ParticipantCaller
 *
 * API version: 1.0.0
 * Contact: aiqueneldar@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/p9139/partcaller/1.0.0/",
		Index,
	},

	Route{
		"AddAbility",
		strings.ToUpper("Post"),
		"/p9139/partcaller/1.0.0/abilities/add",
		AddAbility,
	},

	Route{
		"DeleteAbility",
		strings.ToUpper("Delete"),
		"/p9139/partcaller/1.0.0/abilities/delete",
		DeleteAbility,
	},

	Route{
		"GetAbility",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/abilities/get",
		GetAbility,
	},

	Route{
		"ListAbilities",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/abilities/list",
		ListAbilities,
	},

	Route{
		"ModifyAbility",
		strings.ToUpper("Put"),
		"/p9139/partcaller/1.0.0/abilities/modify",
		ModifyAbility,
	},

	Route{
		"AddEntity",
		strings.ToUpper("Post"),
		"/p9139/partcaller/1.0.0/entities/add",
		AddEntity,
	},

	Route{
		"DeleteEntity",
		strings.ToUpper("Delete"),
		"/p9139/partcaller/1.0.0/entities/delete",
		DeleteEntity,
	},

	Route{
		"GetEntities",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/entities/get",
		GetEntities,
	},

	Route{
		"ListEntities",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/entities/list",
		ListEntities,
	},

	Route{
		"ModifyEntity",
		strings.ToUpper("Put"),
		"/p9139/partcaller/1.0.0/entities/modify",
		ModifyEntity,
	},

	Route{
		"AddEvent",
		strings.ToUpper("Post"),
		"/p9139/partcaller/1.0.0/events/add",
		AddEvent,
	},

	Route{
		"DeleteEvent",
		strings.ToUpper("Delete"),
		"/p9139/partcaller/1.0.0/events/delete",
		DeleteEvent,
	},

	Route{
		"GetEvents",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/events/get",
		GetEvents,
	},

	Route{
		"ListEvents",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/events/list",
		ListEvents,
	},

	Route{
		"ModifyEvent",
		strings.ToUpper("Put"),
		"/p9139/partcaller/1.0.0/events/modify",
		ModifyEvent,
	},

	Route{
		"AddLocation",
		strings.ToUpper("Post"),
		"/p9139/partcaller/1.0.0/locations/add",
		AddLocation,
	},

	Route{
		"DeleteLocation",
		strings.ToUpper("Delete"),
		"/p9139/partcaller/1.0.0/locations/delete",
		DeleteLocation,
	},

	Route{
		"GetLocation",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/locations/get",
		GetLocation,
	},

	Route{
		"ListLocations",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/locations/list",
		ListLocations,
	},

	Route{
		"ModifyLocation",
		strings.ToUpper("Put"),
		"/p9139/partcaller/1.0.0/locations/modify",
		ModifyLocation,
	},

	Route{
		"Addrole",
		strings.ToUpper("Post"),
		"/p9139/partcaller/1.0.0/roles/add",
		Addrole,
	},

	Route{
		"Deleterole",
		strings.ToUpper("Delete"),
		"/p9139/partcaller/1.0.0/roles/delete",
		Deleterole,
	},

	Route{
		"Getrole",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/roles/get",
		Getrole,
	},

	Route{
		"Listroles",
		strings.ToUpper("Get"),
		"/p9139/partcaller/1.0.0/roles/list",
		Listroles,
	},

	Route{
		"Modifyrole",
		strings.ToUpper("Put"),
		"/p9139/partcaller/1.0.0/roles/modify",
		Modifyrole,
	},
}
