version: 0.0
os: linux
files:
  - source: ./PartCallerAPI.zip
    destination: /tmp
Resources:
  - MyFunction: # Replace "MyFunction" with the name of your Lambda function 
      Type: AWS::Lambda::Function
      Properties:
        Name: "PartCallerAPIGetEvent" # Specify the name of your Lambda function
        Alias: "getevent" # Specify the alias for your Lambda function
        CurrentVersion: "1" # Specify the current version of your Lambda function
        TargetVersion: "2" # Specify the version of your Lambda function to deploy
# (Optional) In the Hooks section, specify a validation Lambda function to run during 
# a lifecycle event. Replace "LifeCycleEvent" with BeforeAllowTraffic
# or AfterAllowTraffic.
#Hooks:
#   - LifeCycleEvent: "" # Specify a Lambda validation function between double-quotes.
