version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get install python-pip zip
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r PartCallerAPI.zip **/*.py
  artifacts:
    files:
      - PartCallerAPI.zip
    name: PartCallerAPI