AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  /CodeBuild/DBUser:
    type: 'AWS::SSM::Parameter::Value<String>'
    Default: ''
  /CodeBuild/DBPass:
    type: 'AWS::SSM::Parameter::Value<String>'
    Default: ''

Resources:
  PartCallerAPIEventGet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_event_get.handler
      Runtime: python3.6
      CodeUri: ./
      Description: 'Lambda function to get all Events'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::*:role/PartCallerCloudformationRole'
      Events:
        PartCallerAPI:
          Type: Api
          Properties:
            Path: '/api/event'
            Method: get
      Environment:
        Variables:
          db_username: !Ref /CodeBuild/DBUser
          db_password: !Ref /CodeBuild/DBPass